In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
a=pd.read_csv('train_values.csv')
a.head()

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0       802906               6             487           12198   
1        28830               8             900            2812   
2        94947              21             363            8973   
3       590882              22             418           10694   
4       201944              11             131            1488   

   count_floors_pre_eq  age  area_percentage  height_percentage  \
0                    2   30                6                  5   
1                    2   10                8                  7   
2                    2   10                5                  5   
3                    2   10                6                  5   
4                    3   30                8                  9   

  land_surface_condition foundation_type  ... has_secondary_use_agriculture  \
0                      t               r  ...                             0   
1                      o               r  ...                             0   
2                      t               r  ...                             0   
3                      t               r  ...                             0   
4                      t               r  ...                             0   

  has_secondary_use_hotel has_secondary_use_rental  \
0                       0                        0   
1                       0                        0   
2                       0                        0   
3                       0                        0   
4                       0                        0   

  has_secondary_use_institution has_secondary_use_school  \
0                             0                        0   
1                             0                        0   
2                             0                        0   
3                             0                        0   
4                             0                        0   

   has_secondary_use_industry  has_secondary_use_health_post  \
0                           0                              0   
1                           0                              0   
2                           0                              0   
3                           0                              0   
4                           0                              0   

   has_secondary_use_gov_office  has_secondary_use_use_police  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

   has_secondary_use_other  
0                        0  
1                        0  
2                        0  
3                        0  
4                        0  

[5 rows x 39 columns]

In [3]:
b=pd.read_csv('train_labels.csv')
b.head()

building_id  damage_grade
0       802906             3
1        28830             2
2        94947             3
3       590882             2
4       201944             3

In [4]:
df=pd.merge(a,b,sort=False)
df.head()

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0       802906               6             487           12198   
1        28830               8             900            2812   
2        94947              21             363            8973   
3       590882              22             418           10694   
4       201944              11             131            1488   

   count_floors_pre_eq  age  area_percentage  height_percentage  \
0                    2   30                6                  5   
1                    2   10                8                  7   
2                    2   10                5                  5   
3                    2   10                6                  5   
4                    3   30                8                  9   

  land_surface_condition foundation_type  ... has_secondary_use_hotel  \
0                      t               r  ...                       0   
1                      o               r  ...                       0   
2                      t               r  ...                       0   
3                      t               r  ...                       0   
4                      t               r  ...                       0   

  has_secondary_use_rental has_secondary_use_institution  \
0                        0                             0   
1                        0                             0   
2                        0                             0   
3                        0                             0   
4                        0                             0   

  has_secondary_use_school has_secondary_use_industry  \
0                        0                          0   
1                        0                          0   
2                        0                          0   
3                        0                          0   
4                        0                          0   

   has_secondary_use_health_post  has_secondary_use_gov_office  \
0                              0                             0   
1                              0                             0   
2                              0                             0   
3                              0                             0   
4                              0                             0   

   has_secondary_use_use_police  has_secondary_use_other  damage_grade  
0                             0                        0             3  
1                             0                        0             2  
2                             0                        0             3  
3                             0                        0             2  
4                             0                        0             3  

[5 rows x 40 columns]

In [5]:
pd.set_option('display.max_columns', None)
df.head()

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0       802906               6             487           12198   
1        28830               8             900            2812   
2        94947              21             363            8973   
3       590882              22             418           10694   
4       201944              11             131            1488   

   count_floors_pre_eq  age  area_percentage  height_percentage  \
0                    2   30                6                  5   
1                    2   10                8                  7   
2                    2   10                5                  5   
3                    2   10                6                  5   
4                    3   30                8                  9   

  land_surface_condition foundation_type roof_type ground_floor_type  \
0                      t               r         n                 f   
1                      o               r         n                 x   
2                      t               r         n                 f   
3                      t               r         n                 f   
4                      t               r         n                 f   

  other_floor_type position plan_configuration  has_superstructure_adobe_mud  \
0                q        t                  d                             1   
1                q        s                  d                             0   
2                x        t                  d                             0   
3                x        s                  d                             0   
4                x        s                  d                             1   

   has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  \
0                                    1                              0   
1                                    1                              0   
2                                    1                              0   
3                                    1                              0   
4                                    0                              0   

   has_superstructure_cement_mortar_stone  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   has_superstructure_mud_mortar_brick  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   

   has_superstructure_cement_mortar_brick  has_superstructure_timber  \
0                                       0                          0   
1                                       0                          0   
2                                       0                          0   
3                                       0                          1   
4                                       0                          0   

   has_superstructure_bamboo  has_superstructure_rc_non_engineered  \
0                          0                                     0   
1                          0                                     0   
2                          0                                     0   
3                          1                                     0   
4                          0                                     0   

   has_superstructure_rc_engineered  has_superstructure_other  \
0                                 0                         0   
1                                 0                         0   
2                                 0                         0   
3                                 0                         0   
4                                 0                         0   

  legal_ownership_status  count_families  has_secondary_use  \
0                 

In [6]:
df.shape

(260601, 40)

In [7]:
df.describe()

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
count  2.606010e+05   260601.000000   260601.000000   260601.000000   
mean   5.256755e+05       13.900353      701.074685     6257.876148   
std    3.045450e+05        8.033617      412.710734     3646.369645   
min    4.000000e+00        0.000000        0.000000        0.000000   
25%    2.611900e+05        7.000000      350.000000     3073.000000   
50%    5.257570e+05       12.000000      702.000000     6270.000000   
75%    7.897620e+05       21.000000     1050.000000     9412.000000   
max    1.052934e+06       30.000000     1427.000000    12567.000000   

       count_floors_pre_eq            age  area_percentage  height_percentage  \
count        260601.000000  260601.000000    260601.000000      260601.000000   
mean              2.129723      26.535029         8.018051           5.434365   
std               0.727665      73.565937         4.392231           1.918418   
min               1.000000       0.000000         1.000000           2.000000   
25%               2.000000      10.000000         5.000000           4.000000   
50%               2.000000      15.000000         7.000000           5.000000   
75%               2.000000      30.000000         9.000000           6.000000   
max               9.000000     995.000000       100.000000          32.000000   

       has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  \
count                 260601.000000                        260601.000000   
mean                       0.088645                             0.761935   
std                        0.284231                             0.425900   
min                        0.000000                             0.000000   
25%                        0.000000                             1.000000   
50%                        0.000000                             1.000000   
75%                        0.000000                             1.000000   
max                        1.000000                             1.000000   

       has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  \
count                  260601.000000                           260601.000000   
mean                        0.034332                                0.018235   
std                         0.182081                                0.133800   
min                         0.000000                                0.000000   
25%                         0.000000                                0.000000   
50%                         0.000000                                0.000000   
75%                         0.000000                                0.000000   
max                         1.000000                                1.000000   

       has_superstructure_mud_mortar_brick  \
count                        260601.000000   
mean                              0.068154   
std                               0.252010   
min                               0.000000   
25%                               0.000000   
50%                               0.000000   
75%                               0.000000   
max                               1.000000   

       has_superstructure_cement_mortar_brick  has_superstructure_timber  \
count                           260601.000000              260601.000000   
mean                                 0.075268                   0.254988   
std                                  0.263824                   0.435855   
min                                  0.000000                   0.000000   
25%                                  0.000000                   0.000000   
50%                                  0.000000                   0.000000   
75%                                  0.000000                   1.000000   
max                                  1.000000                   1.000000   

       has_superstructure_bamboo  has_superstructure_rc_non_engineered  \
count              260601.000000                         2

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 260601 entries, 0 to 260600
Data columns (total 40 columns):
building_id                               260601 non-null int64
geo_level_1_id                            260601 non-null int64
geo_level_2_id                            260601 non-null int64
geo_level_3_id                            260601 non-null int64
count_floors_pre_eq                       260601 non-null int64
age                                       260601 non-null int64
area_percentage                           260601 non-null int64
height_percentage                         260601 non-null int64
land_surface_condition                    260601 non-null object
foundation_type                           260601 non-null object
roof_type                                 260601 non-null object
ground_floor_type                         260601 non-null object
other_floor_type                          260601 non-null object
position                                  260601 non

In [9]:
df.isnull().sum().sum()

0

In [10]:
df.describe(include='O')

land_surface_condition foundation_type roof_type ground_floor_type  \
count                  260601          260601    260601            260601   
unique                      3               5         3                 5   
top                         t               r         n                 f   
freq                   216757          219196    182842            209619   

       other_floor_type position plan_configuration legal_ownership_status  
count            260601   260601             260601                 260601  
unique                4        4                 10                      4  
top                   q        s                  d                      v  
freq             165282   202090             250072                 250939

In [11]:
df_new=pd.get_dummies(df,columns=['land_surface_condition','foundation_type','roof_type','ground_floor_type','other_floor_type','position','plan_configuration','legal_ownership_status'])

df_new.head()

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0       802906               6             487           12198   
1        28830               8             900            2812   
2        94947              21             363            8973   
3       590882              22             418           10694   
4       201944              11             131            1488   

   count_floors_pre_eq  age  area_percentage  height_percentage  \
0                    2   30                6                  5   
1                    2   10                8                  7   
2                    2   10                5                  5   
3                    2   10                6                  5   
4                    3   30                8                  9   

   has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  \
0                             1                                    1   
1                             0                                    1   
2                             0                                    1   
3                             0                                    1   
4                             1                                    0   

   has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  \
0                              0                                       0   
1                              0                                       0   
2                              0                                       0   
3                              0                                       0   
4                              0                                       0   

   has_superstructure_mud_mortar_brick  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   

   has_superstructure_cement_mortar_brick  has_superstructure_timber  \
0                                       0                          0   
1                                       0                          0   
2                                       0                          0   
3                                       0                          1   
4                                       0                          0   

   has_superstructure_bamboo  has_superstructure_rc_non_engineered  \
0                          0                                     0   
1                          0                                     0   
2                          0                                     0   
3                          1                                     0   
4                          0                                     0   

   has_superstructure_rc_engineered  has_superstructure_other  count_families  \
0                                 0                         0               1   
1                                 0                         0               1   
2                                 0                         0               1   
3                                 0                         0               1   
4                                 0                         0               1   

   has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  \
0                  0                              0                        0   
1                  0                              0                        0   
2                  0                              0                        0   
3                  0                              0                        0   
4                  0                              0                        0   

   has_secondary_use_rental  has_secondary_use_institution  \
0                         0                              0   
1                         0                              0   
2                         0                         

In [12]:
df_new.shape

(260601, 70)

In [13]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier,VotingClassifier,BaggingClassifier
from sklearn.metrics import classification_report,confusion_matrix,f1_score,accuracy_score

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X=df_new.drop(['building_id','damage_grade'],axis=1)
y=df_new['damage_grade']

In [16]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [17]:
# lr=LogisticRegressionCV(max_iter=100000)

In [18]:
# lr.fit(X_train,y_train)

In [19]:
# pred_lr=lr.predict(X_test)

In [20]:
# print(classification_report(y_test,pred_lr))

In [21]:
# print(confusion_matrix(y_test,pred_lr))

In [22]:
# print(accuracy_score(y_test,pred_lr))

In [23]:
# print(f1_score(y_test,pred_lr,average='micro'))

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc=StandardScaler()

In [26]:
X_new=pd.DataFrame(sc.fit_transform(X),columns=X.columns)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.3, random_state=42)

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
lr=LogisticRegression(max_iter=100000)

In [30]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
pred_lr=lr.predict(X_test)

In [32]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           1       0.58      0.30      0.39      7601
           2       0.60      0.87      0.71     44414
           3       0.54      0.20      0.30     26166

    accuracy                           0.59     78181
   macro avg       0.57      0.46      0.47     78181
weighted avg       0.58      0.59      0.54     78181



In [33]:
print(confusion_matrix(y_test,pred_lr))

[[ 2261  5145   195]
 [ 1520 38549  4345]
 [  139 20710  5317]]


In [34]:
print(accuracy_score(y_test,pred_lr))

0.5900026860746217


In [35]:
print(f1_score(y_test,pred_lr,average='micro'))

0.5900026860746217


In [36]:
import xgboost as xgb

In [37]:
xgbc=xgb.XGBClassifier()

In [38]:
xgbc.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [39]:
pred_xgbc=xgbc.predict(X_test)

In [40]:
print(classification_report(y_test,pred_xgbc))

              precision    recall  f1-score   support

           1       0.70      0.45      0.55      7601
           2       0.72      0.85      0.78     44414
           3       0.75      0.59      0.66     26166

    accuracy                           0.73     78181
   macro avg       0.72      0.63      0.66     78181
weighted avg       0.73      0.73      0.72     78181



In [41]:
print(confusion_matrix(y_test,pred_xgbc))

[[ 3405  4102    94]
 [ 1341 37928  5145]
 [   97 10581 15488]]


In [42]:
print(accuracy_score(y_test,pred_xgbc))

0.7267878384773794


In [43]:
print(f1_score(y_test,pred_xgbc,average='micro'))

0.7267878384773795


In [44]:
rf = RandomForestClassifier(random_state=42)

In [45]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [46]:
pred_rf=rf.predict(X_test)

In [47]:
print(classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           1       0.66      0.47      0.55      7601
           2       0.72      0.82      0.77     44414
           3       0.71      0.60      0.65     26166

    accuracy                           0.71     78181
   macro avg       0.69      0.63      0.65     78181
weighted avg       0.71      0.71      0.71     78181



In [48]:
print(confusion_matrix(y_test,pred_rf))

[[ 3569  3850   182]
 [ 1703 36521  6190]
 [  172 10402 15592]]


In [49]:
print(accuracy_score(y_test,pred_rf))

0.7122190813624794


In [50]:
print(f1_score(y_test,pred_rf,average='micro'))

0.7122190813624794


In [51]:
ada=AdaBoostClassifier()

In [52]:
ada.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [53]:
pred_ada=ada.predict(X_test)

In [54]:
print(classification_report(y_test,pred_ada))

              precision    recall  f1-score   support

           1       0.57      0.35      0.43      7601
           2       0.63      0.88      0.74     44414
           3       0.71      0.33      0.45     26166

    accuracy                           0.64     78181
   macro avg       0.64      0.52      0.54     78181
weighted avg       0.65      0.64      0.61     78181



In [55]:
print(confusion_matrix(y_test,pred_ada))

[[ 2627  4951    23]
 [ 1872 39018  3524]
 [   92 17503  8571]]


In [56]:
print(accuracy_score(y_test,pred_ada))

0.6423043962087975


In [57]:
print(f1_score(y_test,pred_ada,average='micro'))

0.6423043962087975


In [58]:
gbc=GradientBoostingClassifier()

In [59]:
gbc.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [60]:
pred_gbc=gbc.predict(X_test)

In [61]:
print(classification_report(y_test,pred_gbc))

              precision    recall  f1-score   support

           1       0.65      0.38      0.47      7601
           2       0.67      0.86      0.76     44414
           3       0.72      0.46      0.56     26166

    accuracy                           0.68     78181
   macro avg       0.68      0.57      0.60     78181
weighted avg       0.69      0.68      0.66     78181



In [62]:
print(confusion_matrix(y_test,pred_gbc))

[[ 2854  4688    59]
 [ 1466 38299  4649]
 [  100 13911 12155]]


In [63]:
print(accuracy_score(y_test,pred_gbc))

0.6818536473056114


In [64]:
print(f1_score(y_test,pred_gbc,average='micro'))

0.6818536473056114


In [65]:
dt=DecisionTreeClassifier()

In [66]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [67]:
pred_dt=dt.predict(X_test)

In [68]:
print(classification_report(y_test,pred_dt))

              precision    recall  f1-score   support

           1       0.49      0.50      0.49      7601
           2       0.71      0.71      0.71     44414
           3       0.62      0.62      0.62     26166

    accuracy                           0.66     78181
   macro avg       0.60      0.61      0.61     78181
weighted avg       0.66      0.66      0.66     78181



In [69]:
print(confusion_matrix(y_test,pred_dt))

[[ 3811  3242   548]
 [ 3513 31400  9501]
 [  532  9515 16119]]


In [70]:
print(accuracy_score(y_test,pred_dt))

0.6565533825353986


In [71]:
print(f1_score(y_test,pred_dt,average='micro'))

0.6565533825353986


In [72]:
bgc=BaggingClassifier()

In [73]:
bgc.fit(X_train,y_train)

BaggingClassifier(base_estimator=None, bootstrap=True, bootstrap_features=False,
                  max_features=1.0, max_samples=1.0, n_estimators=10,
                  n_jobs=None, oob_score=False, random_state=None, verbose=0,
                  warm_start=False)

In [74]:
pred_bgc=bgc.predict(X_test)

In [75]:
print(classification_report(y_test,pred_bgc))

              precision    recall  f1-score   support

           1       0.58      0.54      0.56      7601
           2       0.73      0.80      0.76     44414
           3       0.71      0.60      0.65     26166

    accuracy                           0.71     78181
   macro avg       0.67      0.65      0.66     78181
weighted avg       0.71      0.71      0.70     78181



In [76]:
print(confusion_matrix(y_test,pred_bgc))

[[ 4098  3254   249]
 [ 2629 35456  6329]
 [  316 10095 15755]]


In [77]:
print(accuracy_score(y_test,pred_bgc))

0.707448101201059


In [78]:
print(f1_score(y_test,pred_bgc,average='micro'))

0.7074481012010592


In [79]:
ensemble=[('Decision Tree',dt),('Random Forest',rf),('Bagging',bgc),('Gradient Boosting',gbc),('AdaBoosting',ada),('XGBClassifier',xgbc)]

In [80]:
vc=VotingClassifier(estimators=ensemble)

In [81]:
vc.fit(X_train,y_train)

VotingClassifier(estimators=[('Decision Tree',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     presort='deprecated',
                                                     random_stat

In [82]:
pred_vc=vc.predict(X_test)

In [83]:
print(classification_report(y_test,pred_vc))

              precision    recall  f1-score   support

           1       0.65      0.50      0.57      7601
           2       0.70      0.88      0.78     44414
           3       0.80      0.50      0.61     26166

    accuracy                           0.72     78181
   macro avg       0.72      0.63      0.66     78181
weighted avg       0.73      0.72      0.71     78181



In [84]:
print(confusion_matrix(y_test,pred_vc))

[[ 3821  3728    52]
 [ 1859 39288  3267]
 [  160 12940 13066]]


In [85]:
print(accuracy_score(y_test,pred_vc))

0.7185249613077346


In [86]:
print(f1_score(y_test,pred_vc,average='micro'))

0.7185249613077346


In [87]:
test=pd.read_csv('test_values.csv')
test.head()

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0       300051              17             596           11307   
1        99355               6             141           11987   
2       890251              22              19           10044   
3       745817              26              39             633   
4       421793              17             289            7970   

   count_floors_pre_eq  age  area_percentage  height_percentage  \
0                    3   20                7                  6   
1                    2   25               13                  5   
2                    2    5                4                  5   
3                    1    0               19                  3   
4                    3   15                8                  7   

  land_surface_condition foundation_type roof_type ground_floor_type  \
0                      t               r         n                 f   
1                      t               r         n                 f   
2                      t               r         n                 f   
3                      t               r         x                 v   
4                      t               r         q                 f   

  other_floor_type position plan_configuration  has_superstructure_adobe_mud  \
0                q        s                  d                             0   
1                q        s                  d                             0   
2                q        s                  d                             0   
3                j        t                  d                             0   
4                q        t                  d                             0   

   has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  \
0                                    1                              0   
1                                    1                              0   
2                                    1                              0   
3                                    0                              0   
4                                    1                              0   

   has_superstructure_cement_mortar_stone  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   has_superstructure_mud_mortar_brick  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   

   has_superstructure_cement_mortar_brick  has_superstructure_timber  \
0                                       0                          0   
1                                       0                          0   
2                                       0                          0   
3                                       1                          0   
4                                       0                          0   

   has_superstructure_bamboo  has_superstructure_rc_non_engineered  \
0                          0                                     0   
1                          0                                     0   
2                          0                                     0   
3                          0                                     0   
4                          0                                     0   

   has_superstructure_rc_engineered  has_superstructure_other  \
0                                 0                         0   
1                                 0                         0   
2                                 0                         0   
3                                 0                         0   
4                                 0                         0   

  legal_ownership_status  count_families  has_secondary_use  \
0                 

In [88]:
test.shape

(86868, 39)

In [89]:
df_t=pd.get_dummies(test,columns=['land_surface_condition','foundation_type','roof_type','ground_floor_type','other_floor_type','position','plan_configuration','legal_ownership_status'])

df_t.head()

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0       300051              17             596           11307   
1        99355               6             141           11987   
2       890251              22              19           10044   
3       745817              26              39             633   
4       421793              17             289            7970   

   count_floors_pre_eq  age  area_percentage  height_percentage  \
0                    3   20                7                  6   
1                    2   25               13                  5   
2                    2    5                4                  5   
3                    1    0               19                  3   
4                    3   15                8                  7   

   has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  \
0                             0                                    1   
1                             0                                    1   
2                             0                                    1   
3                             0                                    0   
4                             0                                    1   

   has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  \
0                              0                                       0   
1                              0                                       0   
2                              0                                       0   
3                              0                                       0   
4                              0                                       0   

   has_superstructure_mud_mortar_brick  \
0                                    0   
1                                    0   
2                                    0   
3                                    0   
4                                    0   

   has_superstructure_cement_mortar_brick  has_superstructure_timber  \
0                                       0                          0   
1                                       0                          0   
2                                       0                          0   
3                                       1                          0   
4                                       0                          0   

   has_superstructure_bamboo  has_superstructure_rc_non_engineered  \
0                          0                                     0   
1                          0                                     0   
2                          0                                     0   
3                          0                                     0   
4                          0                                     0   

   has_superstructure_rc_engineered  has_superstructure_other  count_families  \
0                                 0                         0               1   
1                                 0                         0               1   
2                                 0                         0               1   
3                                 0                         0               2   
4                                 0                         0               1   

   has_secondary_use  has_secondary_use_agriculture  has_secondary_use_hotel  \
0                  0                              0                        0   
1                  1                              1                        0   
2                  0                              0                        0   
3                  1                              0                        0   
4                  0                              0                        0   

   has_secondary_use_rental  has_secondary_use_institution  \
0                         0                              0   
1                         0                              0   
2                         0                         

In [90]:
df_t.shape

(86868, 69)

In [91]:
b=df_t['building_id']

In [92]:
df_t.drop(['building_id'],axis=1,inplace=True)

In [93]:
X_t=pd.DataFrame(sc.fit_transform(df_t),columns=df_t.columns)

In [94]:
pred_xgbc_test=xgbc.predict(X_t)

In [95]:
new=pd.DataFrame()

In [96]:
new['building_id']=pd.Series(b)

In [97]:
new['damage_grade']=pd.Series(pred_xgbc_test)

In [98]:
new['damage_grade'].value_counts()

2    59539
3    22121
1     5208
Name: damage_grade, dtype: int64

In [99]:
new

building_id  damage_grade
0           300051             3
1            99355             2
2           890251             2
3           745817             1
4           421793             3
...            ...           ...
86863       310028             2
86864       663567             3
86865      1049160             2
86866       442785             2
86867       501372             2

[86868 rows x 2 columns]

In [100]:
new.to_csv (r'C:\Users\lenovo\Desktop\Python\Driven Data\Submission.csv', index = False)